/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HotProductList: typeof import('./src/components/HotProductList.vue')['default']
    NavTitle: typeof import('./src/components/NavTitle.vue')['default']
    NutButton: typeof import('@nutui/nutui')['Button']
    UpdateFIle: typeof import('./src/components/UpdateFIle.vue')['default']
  }
}
